name: Publish lightspark_wallet to pub.dev

on:
  push:
    tags:
      - "lightspark_wallet-v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Check Version
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/lightspark-wallet-v[0-9]+.[0-9]+.[0-9]+.*$ ]]; then
            echo "GITHUB_REF is not a tag"
            exit 0
          fi
          tag_version=$(echo $GITHUB_REF | sed -e 's/refs\/tags\/lightspark-wallet-v//g')
          echo "tag_version=$tag_version"
          current_version=$(cat lightspark_wallet/pubspec.yaml | grep '^version:' | sed -e 's/version: //g')
          echo "current_version=$current_version"
          if [ "$tag_version" != "$current_version" ]; then
            echo "Tag version and pubspec.yaml version are not the same"
            exit 1
          fi
      - name: Install dependencies
        run: flutter pub get
        working-directory: lightspark_wallet
      - name: Analyze
        run: flutter analyze
        working-directory: lightspark_wallet
      - name: Build android
        run: flutter build aar
        working-directory: lightspark_wallet
      - name: Build ios
        run: flutter build ios --no-codesign
        working-directory: lightspark_wallet
      - name: Publish to pub.dev
        run: flutter pub publish
        working-directory: lightspark_wallet
